import { pgTable, uuid, varchar, integer, numeric, text, jsonb, timestamp } from 'drizzle-orm/pg-core';
import { tenants } from './tenants.js';
import { tenantUsers } from './users.js';

export const usageLogs = pgTable('usage_logs', {
  logId: uuid('log_id').primaryKey().defaultRandom(),
  tenantId: uuid('tenant_id').notNull().references(() => tenants.tenantId),
  userId: uuid('user_id').references(() => tenantUsers.userId),
  organizationId: uuid('organization_id').references(() => tenants.tenantId),
  locationId: uuid('location_id'),
  app: varchar('app', { length: 50 }).notNull(),
  endpoint: varchar('endpoint', { length: 255 }).notNull(),
  method: varchar('method', { length: 10 }).notNull(),
  statusCode: integer('status_code'),
  responseTime: numeric('response_time', { precision: 8, scale: 2 }),
  source: varchar('source', { length: 50 }).notNull(),
  ipAddress: varchar('ip_address', { length: 45 }),
  userAgent: text('user_agent'),
  operationCode: varchar('operation_code', { length: 255 }),
  creditConsumed: numeric('credit_consumed', { precision: 10, scale: 4 }).default('0'),
  creditBatchId: uuid('credit_batch_id'),
  pricingMode: varchar('pricing_mode', { length: 20 }).default('credits'),
  requestSize: integer('request_size'),
  responseSize: integer('response_size'),
  metadata: jsonb('metadata').default({}),
  errorMessage: text('error_message'),
  errorStack: text('error_stack'),
  createdAt: timestamp('created_at').defaultNow(),
});

export const usageMetricsDaily = pgTable('usage_metrics_daily', {
  metricId: uuid('metric_id').primaryKey().defaultRandom(),
  tenantId: uuid('tenant_id').notNull().references(() => tenants.tenantId),
  organizationId: uuid('organization_id').references(() => tenants.tenantId),
  locationId: uuid('location_id'),
  app: varchar('app', { length: 50 }).notNull(),
  date: timestamp('date').notNull(),
  apiCalls: integer('api_calls').default(0),
  storageUsed: numeric('storage_used', { precision: 15, scale: 2 }).default('0'),
  activeUsers: integer('active_users').default(0),
  totalRequests: integer('total_requests').default(0),
  creditConsumed: numeric('credit_consumed', { precision: 15, scale: 4 }).default('0'),
  creditBatchesUsed: jsonb('credit_batches_used').default([]),
  avgResponseTime: numeric('avg_response_time', { precision: 8, scale: 2 }).default('0'),
  errorCount: integer('error_count').default(0),
  featureUsage: jsonb('feature_usage').default({}),
  usageBySource: jsonb('usage_by_source').default({}),
  createdAt: timestamp('created_at').defaultNow(),
  updatedAt: timestamp('updated_at').defaultNow(),
});
