import { pgTable, index, unique, pgEnum, uuid, varchar, jsonb, boolean, timestamp, integer, numeric, text, date, foreignKey, inet } from "drizzle-orm/pg-core"
  import { sql } from "drizzle-orm"

export const aalLevel = pgEnum("aal_level", ['aal3', 'aal2', 'aal1'])
export const codeChallengeMethod = pgEnum("code_challenge_method", ['plain', 's256'])
export const factorStatus = pgEnum("factor_status", ['verified', 'unverified'])
export const factorType = pgEnum("factor_type", ['phone', 'webauthn', 'totp'])
export const oneTimeTokenType = pgEnum("one_time_token_type", ['phone_change_token', 'email_change_token_current', 'email_change_token_new', 'recovery_token', 'reauthentication_token', 'confirmation_token'])
export const enumUserOrganizationsStatus = pgEnum("enum_user_organizations_status", ['inactive', 'active', 'invited'])
export const action = pgEnum("action", ['ERROR', 'TRUNCATE', 'DELETE', 'UPDATE', 'INSERT'])
export const equalityOp = pgEnum("equality_op", ['in', 'gte', 'gt', 'lte', 'lt', 'neq', 'eq'])
export const buckettype = pgEnum("buckettype", ['ANALYTICS', 'STANDARD'])


export const tenants = pgTable("tenants", {
	tenantId: uuid("tenant_id").defaultRandom().primaryKey().notNull(),
	companyName: varchar("company_name", { length: 255 }).notNull(),
	subdomain: varchar("subdomain", { length: 100 }).notNull(),
	kindeOrgId: varchar("kinde_org_id", { length: 255 }).notNull(),
	adminEmail: varchar("admin_email", { length: 255 }).notNull(),
	logoUrl: varchar("logo_url", { length: 500 }),
	primaryColor: varchar("primary_color", { length: 7 }).default('#2563eb'::character varying),
	customDomain: varchar("custom_domain", { length: 255 }),
	brandingConfig: jsonb("branding_config").default({}),
	companySize: varchar("company_size", { length: 50 }),
	industry: varchar("industry", { length: 100 }),
	timezone: varchar("timezone", { length: 50 }).default('UTC'::character varying),
	country: varchar("country", { length: 100 }),
	isActive: boolean("is_active").default(true),
	isVerified: boolean("is_verified").default(false),
	trialEndsAt: timestamp("trial_ends_at", { mode: 'string' }),
	settings: jsonb("settings").default({}),
	onboardedAt: timestamp("onboarded_at", { mode: 'string' }),
	lastActivityAt: timestamp("last_activity_at", { mode: 'string' }),
	createdAt: timestamp("created_at", { mode: 'string' }).defaultNow(),
	updatedAt: timestamp("updated_at", { mode: 'string' }).defaultNow(),
	logo: varchar("logo", { length: 500 }),
	customBranding: jsonb("custom_branding").default({}),
	onboardingCompleted: boolean("onboarding_completed").default(false),
	onboardingStep: varchar("onboarding_step", { length: 50 }),
	onboardingProgress: jsonb("onboarding_progress").default({}),
	onboardingStartedAt: timestamp("onboarding_started_at", { mode: 'string' }),
	setupCompletionRate: integer("setup_completion_rate").default(0),
	trialStartedAt: timestamp("trial_started_at", { mode: 'string' }),
	trialStatus: varchar("trial_status", { length: 20 }).default('active'::character varying),
	subscriptionStatus: varchar("subscription_status", { length: 20 }).default('trial'::character varying),
	featuresEnabled: jsonb("features_enabled").default({}),
	firstLoginAt: timestamp("first_login_at", { mode: 'string' }),
	initialSetupData: jsonb("initial_setup_data").default({}),
	stripeCustomerId: varchar("stripe_customer_id", { length: 255 }),
	legalCompanyName: varchar("legal_company_name", { length: 255 }),
	companyId: varchar("company_id", { length: 100 }),
	dunsNumber: varchar("duns_number", { length: 50 }),
	companyType: varchar("company_type", { length: 100 }),
	ownership: varchar("ownership", { length: 100 }),
	annualRevenue: numeric("annual_revenue", { precision: 15, scale:  2 }),
	numberOfEmployees: integer("number_of_employees"),
	tickerSymbol: varchar("ticker_symbol", { length: 20 }),
	website: varchar("website", { length: 500 }),
	companyDescription: text("company_description"),
	foundedDate: date("founded_date"),
	billingStreet: varchar("billing_street", { length: 255 }),
	billingCity: varchar("billing_city", { length: 100 }),
	billingState: varchar("billing_state", { length: 100 }),
	billingZip: varchar("billing_zip", { length: 20 }),
	billingCountry: varchar("billing_country", { length: 100 }),
	shippingStreet: varchar("shipping_street", { length: 255 }),
	shippingCity: varchar("shipping_city", { length: 100 }),
	shippingState: varchar("shipping_state", { length: 100 }),
	shippingZip: varchar("shipping_zip", { length: 20 }),
	shippingCountry: varchar("shipping_country", { length: 100 }),
	phone: varchar("phone", { length: 50 }),
	fax: varchar("fax", { length: 50 }),
	defaultLanguage: varchar("default_language", { length: 10 }).default('en'::character varying),
	defaultLocale: varchar("default_locale", { length: 20 }).default('en-US'::character varying),
	defaultCurrency: varchar("default_currency", { length: 3 }).default('USD'::character varying),
	multiCurrencyEnabled: boolean("multi_currency_enabled").default(false),
	advancedCurrencyManagement: boolean("advanced_currency_management").default(false),
	defaultTimezone: varchar("default_timezone", { length: 50 }).default('UTC'::character varying),
	firstDayOfWeek: integer("first_day_of_week").default(1),
	gstin: varchar("gstin", { length: 15 }),
},
(table) => {
	return {
		idxTenantsIndustry: index("idx_tenants_industry").on(table.industry),
		idxTenantsCompanyType: index("idx_tenants_company_type").on(table.companyType),
		idxTenantsCompanySize: index("idx_tenants_company_size").on(table.companySize),
		idxTenantsCountry: index("idx_tenants_country").on(table.country),
		idxTenantsBillingCountry: index("idx_tenants_billing_country").on(table.billingCountry),
		idxTenantsShippingCountry: index("idx_tenants_shipping_country").on(table.shippingCountry),
		tenantsSubdomainUnique: unique("tenants_subdomain_unique").on(table.subdomain),
		tenantsKindeOrgIdUnique: unique("tenants_kinde_org_id_unique").on(table.kindeOrgId),
	}
});

export const activityLogs = pgTable("activity_logs", {
	logId: uuid("log_id").defaultRandom().primaryKey().notNull(),
	userId: uuid("user_id").references(() => tenantUsers.userId),
	tenantId: uuid("tenant_id").references(() => tenants.tenantId),
	appId: uuid("app_id").references(() => applications.appId),
	action: varchar("action", { length: 100 }).notNull(),
	resourceType: varchar("resource_type", { length: 50 }),
	resourceId: varchar("resource_id", { length: 255 }),
	metadata: jsonb("metadata"),
	ipAddress: varchar("ip_address", { length: 45 }),
	userAgent: text("user_agent"),
	createdAt: timestamp("created_at", { mode: 'string' }).defaultNow(),
});

export const applications = pgTable("applications", {
	appId: uuid("app_id").defaultRandom().primaryKey().notNull(),
	appCode: varchar("app_code", { length: 50 }).notNull(),
	appName: varchar("app_name", { length: 100 }).notNull(),
	description: text("description"),
	icon: varchar("icon", { length: 255 }),
	baseUrl: varchar("base_url", { length: 255 }).notNull(),
	status: varchar("status", { length: 20 }).default('active'::character varying).notNull(),
	version: varchar("version", { length: 20 }),
	isCore: boolean("is_core").default(false),
	sortOrder: integer("sort_order").default(0),
	createdAt: timestamp("created_at", { mode: 'string' }).defaultNow(),
	updatedAt: timestamp("updated_at", { mode: 'string' }).defaultNow(),
},
(table) => {
	return {
		applicationsAppCodeUnique: unique("applications_app_code_unique").on(table.appCode),
	}
});

export const auditLogs = pgTable("audit_logs", {
	logId: uuid("log_id").defaultRandom().primaryKey().notNull(),
	tenantId: uuid("tenant_id").notNull().references(() => tenants.tenantId),
	userId: uuid("user_id").references(() => tenantUsers.userId),
	action: varchar("action", { length: 100 }).notNull(),
	resourceType: varchar("resource_type", { length: 50 }).notNull(),
	resourceId: varchar("resource_id", { length: 255 }),
	oldValues: jsonb("old_values"),
	newValues: jsonb("new_values"),
	details: jsonb("details"),
	ipAddress: varchar("ip_address", { length: 45 }),
	userAgent: text("user_agent"),
	createdAt: timestamp("created_at", { mode: 'string' }).defaultNow(),
});

export const organizationApplications = pgTable("organization_applications", {
	id: uuid("id").defaultRandom().primaryKey().notNull(),
	tenantId: uuid("tenant_id").references(() => tenants.tenantId),
	appId: uuid("app_id").references(() => applications.appId),
	isEnabled: boolean("is_enabled").default(true),
	enabledModules: jsonb("enabled_modules"),
	customPermissions: jsonb("custom_permissions"),
	licenseCount: integer("license_count").default(0),
	maxUsers: integer("max_users"),
	subscriptionTier: varchar("subscription_tier", { length: 50 }),
	expiresAt: timestamp("expires_at", { mode: 'string' }),
	createdAt: timestamp("created_at", { mode: 'string' }).defaultNow(),
	updatedAt: timestamp("updated_at", { mode: 'string' }).defaultNow(),
});

export const payments = pgTable("payments", {
	paymentId: uuid("payment_id").defaultRandom().primaryKey().notNull(),
	tenantId: uuid("tenant_id").notNull().references(() => tenants.tenantId),
	subscriptionId: uuid("subscription_id").references(() => subscriptions.subscriptionId),
	stripePaymentIntentId: varchar("stripe_payment_intent_id", { length: 255 }),
	stripeInvoiceId: varchar("stripe_invoice_id", { length: 255 }),
	amount: numeric("amount", { precision: 10, scale:  2 }).notNull(),
	currency: varchar("currency", { length: 3 }).default('USD'::character varying),
	status: varchar("status", { length: 20 }).notNull(),
	paymentMethod: varchar("payment_method", { length: 50 }),
	invoiceNumber: varchar("invoice_number", { length: 50 }),
	description: text("description"),
	metadata: jsonb("metadata").default({}),
	paidAt: timestamp("paid_at", { mode: 'string' }),
	failedAt: timestamp("failed_at", { mode: 'string' }),
	refundedAt: timestamp("refunded_at", { mode: 'string' }),
	createdAt: timestamp("created_at", { mode: 'string' }).defaultNow(),
	stripeChargeId: varchar("stripe_charge_id", { length: 255 }),
	stripeRefundId: varchar("stripe_refund_id", { length: 255 }),
	stripeDisputeId: varchar("stripe_dispute_id", { length: 255 }),
	amountRefunded: numeric("amount_refunded", { precision: 10, scale:  2 }).default('0'),
	amountDisputed: numeric("amount_disputed", { precision: 10, scale:  2 }).default('0'),
	paymentMethodDetails: jsonb("payment_method_details").default({}),
	paymentType: varchar("payment_type", { length: 30 }).default('subscription'::character varying),
	billingReason: varchar("billing_reason", { length: 50 }),
	prorationAmount: numeric("proration_amount", { precision: 10, scale:  2 }).default('0'),
	creditAmount: numeric("credit_amount", { precision: 10, scale:  2 }).default('0'),
	refundReason: varchar("refund_reason", { length: 100 }),
	refundRequestedBy: uuid("refund_requested_by").references(() => tenants.tenantId),
	isPartialRefund: boolean("is_partial_refund").default(false),
	disputeReason: varchar("dispute_reason", { length: 100 }),
	disputeStatus: varchar("dispute_status", { length: 30 }),
	disputeEvidenceSubmitted: boolean("dispute_evidence_submitted").default(false),
	taxAmount: numeric("tax_amount", { precision: 10, scale:  2 }).default('0'),
	taxRate: numeric("tax_rate", { precision: 5, scale:  4 }).default('0'),
	taxRegion: varchar("tax_region", { length: 50 }),
	processingFees: numeric("processing_fees", { precision: 10, scale:  2 }).default('0'),
	netAmount: numeric("net_amount", { precision: 10, scale:  2 }),
	riskLevel: varchar("risk_level", { length: 20 }),
	riskScore: integer("risk_score"),
	fraudDetails: jsonb("fraud_details").default({}),
	stripeRawData: jsonb("stripe_raw_data").default({}),
	disputedAt: timestamp("disputed_at", { mode: 'string' }),
	settledAt: timestamp("settled_at", { mode: 'string' }),
	updatedAt: timestamp("updated_at", { mode: 'string' }).defaultNow(),
});

export const subscriptionActions = pgTable("subscription_actions", {
	actionId: uuid("action_id").defaultRandom().primaryKey().notNull(),
	tenantId: uuid("tenant_id").notNull().references(() => tenants.tenantId),
	subscriptionId: uuid("subscription_id").notNull().references(() => subscriptions.subscriptionId),
	actionType: varchar("action_type", { length: 30 }).notNull(),
	fromPlan: varchar("from_plan", { length: 50 }),
	toPlan: varchar("to_plan", { length: 50 }),
	fromBillingCycle: varchar("from_billing_cycle", { length: 20 }),
	toBillingCycle: varchar("to_billing_cycle", { length: 20 }),
	prorationAmount: numeric("proration_amount", { precision: 10, scale:  2 }).default('0'),
	refundAmount: numeric("refund_amount", { precision: 10, scale:  2 }).default('0'),
	chargeAmount: numeric("charge_amount", { precision: 10, scale:  2 }).default('0'),
	effectiveDate: timestamp("effective_date", { mode: 'string' }).notNull(),
	initiatedBy: uuid("initiated_by").references(() => tenants.tenantId),
	reason: varchar("reason", { length: 100 }),
	adminNotes: text("admin_notes"),
	customerNotes: text("customer_notes"),
	status: varchar("status", { length: 20 }).default('pending'::character varying),
	stripeSubscriptionId: varchar("stripe_subscription_id", { length: 255 }),
	stripeInvoiceId: varchar("stripe_invoice_id", { length: 255 }),
	impactAssessment: jsonb("impact_assessment").default({}),
	rollbackData: jsonb("rollback_data").default({}),
	requestedAt: timestamp("requested_at", { mode: 'string' }).defaultNow(),
	processedAt: timestamp("processed_at", { mode: 'string' }),
	completedAt: timestamp("completed_at", { mode: 'string' }),
	reversedAt: timestamp("reversed_at", { mode: 'string' }),
	createdAt: timestamp("created_at", { mode: 'string' }).defaultNow(),
});

export const trialEvents = pgTable("trial_events", {
	eventId: uuid("event_id").defaultRandom().primaryKey().notNull(),
	tenantId: uuid("tenant_id").notNull().references(() => tenants.tenantId, { onDelete: "cascade" } ),
	subscriptionId: uuid("subscription_id").references(() => subscriptions.subscriptionId, { onDelete: "cascade" } ),
	eventType: varchar("event_type", { length: 50 }).notNull(),
	eventData: jsonb("event_data").default({}),
	userId: uuid("user_id"),
	ipAddress: inet("ip_address"),
	userAgent: text("user_agent"),
	createdAt: timestamp("created_at", { mode: 'string' }).defaultNow(),
},
(table) => {
	return {
		idxTrialEventsSubscription: index("idx_trial_events_subscription").on(table.subscriptionId, table.eventType),
		idxTrialEventsTenant: index("idx_trial_events_tenant").on(table.tenantId, table.eventType, table.createdAt),
		idxTrialEventsTypeDate: index("idx_trial_events_type_date").on(table.eventType, table.createdAt),
	}
});

export const trialRestrictions = pgTable("trial_restrictions", {
	restrictionId: uuid("restriction_id").defaultRandom().primaryKey().notNull(),
	tenantId: uuid("tenant_id").notNull().references(() => tenants.tenantId, { onDelete: "cascade" } ),
	restrictionType: varchar("restriction_type", { length: 50 }).notNull(),
	isActive: boolean("is_active").default(true),
	restrictionData: jsonb("restriction_data").default({}),
	appliedAt: timestamp("applied_at", { mode: 'string' }).defaultNow(),
	removedAt: timestamp("removed_at", { mode: 'string' }),
},
(table) => {
	return {
		idxTrialRestrictionsTenant: index("idx_trial_restrictions_tenant").on(table.tenantId, table.isActive),
		idxTrialRestrictionsType: index("idx_trial_restrictions_type").on(table.restrictionType, table.isActive),
	}
});

export const trialStatusView = pgTable("trial_status_view", {
	tenantId: uuid("tenant_id"),
	subscriptionId: uuid("subscription_id"),
	plan: varchar("plan", { length: 50 }),
	status: varchar("status", { length: 20 }),
	trialStart: timestamp("trial_start", { mode: 'string' }),
	trialEnd: timestamp("trial_end", { mode: 'string' }),
	currentPeriodStart: timestamp("current_period_start", { mode: 'string' }),
	currentPeriodEnd: timestamp("current_period_end", { mode: 'string' }),
	hasEverUpgraded: boolean("has_ever_upgraded"),
	trialToggledOff: boolean("trial_toggled_off"),
	lastReminderSentAt: timestamp("last_reminder_sent_at", { mode: 'string' }),
	reminderCount: integer("reminder_count"),
	companyName: varchar("company_name", { length: 255 }),
	adminEmail: varchar("admin_email", { length: 255 }),
	isExpired: boolean("is_expired"),
	expiryDate: timestamp("expiry_date", { mode: 'string' }),
});

export const usageAlerts = pgTable("usage_alerts", {
	alertId: uuid("alert_id").defaultRandom().primaryKey().notNull(),
	tenantId: uuid("tenant_id").notNull().references(() => tenants.tenantId),
	alertType: varchar("alert_type", { length: 50 }).notNull(),
	severity: varchar("severity", { length: 20 }).notNull(),
	title: varchar("title", { length: 255 }).notNull(),
	message: text("message").notNull(),
	metricType: varchar("metric_type", { length: 50 }).notNull(),
	currentValue: numeric("current_value", { precision: 15, scale:  2 }),
	limitValue: numeric("limit_value", { precision: 15, scale:  2 }),
	percentage: numeric("percentage", { precision: 5, scale:  2 }),
	isRead: boolean("is_read").default(false),
	isSent: boolean("is_sent").default(false),
	sentAt: timestamp("sent_at", { mode: 'string' }),
	readAt: timestamp("read_at", { mode: 'string' }),
	actionRequired: varchar("action_required", { length: 100 }),
	actionTaken: varchar("action_taken", { length: 100 }),
	resolvedAt: timestamp("resolved_at", { mode: 'string' }),
	createdAt: timestamp("created_at", { mode: 'string' }).defaultNow(),
});

export const tenantUsers = pgTable("tenant_users", {
	userId: uuid("user_id").defaultRandom().primaryKey().notNull(),
	tenantId: uuid("tenant_id").notNull().references(() => tenants.tenantId),
	kindeUserId: varchar("kinde_user_id", { length: 255 }),
	email: varchar("email", { length: 255 }).notNull(),
	name: varchar("name", { length: 255 }).notNull(),
	avatar: varchar("avatar", { length: 500 }),
	title: varchar("title", { length: 100 }),
	department: varchar("department", { length: 100 }),
	isActive: boolean("is_active").default(true),
	isVerified: boolean("is_verified").default(false),
	isTenantAdmin: boolean("is_tenant_admin").default(false),
	lastActiveAt: timestamp("last_active_at", { mode: 'string' }),
	lastLoginAt: timestamp("last_login_at", { mode: 'string' }),
	loginCount: integer("login_count").default(0),
	preferences: jsonb("preferences").default({}),
	onboardingCompleted: boolean("onboarding_completed").default(false),
	onboardingStep: varchar("onboarding_step", { length: 50 }),
	createdAt: timestamp("created_at", { mode: 'string' }).defaultNow(),
	updatedAt: timestamp("updated_at", { mode: 'string' }).defaultNow(),
	invitedBy: uuid("invited_by"),
	invitedAt: timestamp("invited_at", { mode: 'string' }),
	firstName: varchar("first_name", { length: 100 }),
	lastName: varchar("last_name", { length: 100 }),
	username: varchar("username", { length: 100 }),
	alias: varchar("alias", { length: 100 }),
	phone: varchar("phone", { length: 50 }),
	mobile: varchar("mobile", { length: 50 }),
	managerId: uuid("manager_id"),
	profileData: jsonb("profile_data").default({}),
},
(table) => {
	return {
		tenantUsersInvitedByTenantUsersUserIdFk: foreignKey({
			columns: [table.invitedBy],
			foreignColumns: [table.userId],
			name: "tenant_users_invited_by_tenant_users_user_id_fk"
		}),
		tenantUsersManagerIdFkey: foreignKey({
			columns: [table.managerId],
			foreignColumns: [table.userId],
			name: "tenant_users_manager_id_fkey"
		}),
	}
});

export const userRoleAssignments = pgTable("user_role_assignments", {
	id: uuid("id").defaultRandom().primaryKey().notNull(),
	userId: uuid("user_id").notNull().references(() => tenantUsers.userId),
	roleId: uuid("role_id").notNull().references(() => customRoles.roleId),
	assignedBy: uuid("assigned_by").notNull().references(() => tenantUsers.userId),
	assignedAt: timestamp("assigned_at", { mode: 'string' }).defaultNow(),
	isTemporary: boolean("is_temporary").default(false),
	expiresAt: timestamp("expires_at", { mode: 'string' }),
	isActive: boolean("is_active").default(true),
	deactivatedAt: timestamp("deactivated_at", { mode: 'string' }),
	deactivatedBy: uuid("deactivated_by").references(() => tenantUsers.userId),
});

export const userSessions = pgTable("user_sessions", {
	sessionId: uuid("session_id").defaultRandom().primaryKey().notNull(),
	userId: uuid("user_id").notNull().references(() => tenantUsers.userId),
	tenantId: uuid("tenant_id").notNull().references(() => tenants.tenantId),
	sessionToken: varchar("session_token", { length: 255 }).notNull(),
	ipAddress: varchar("ip_address", { length: 45 }),
	userAgent: text("user_agent"),
	loginAt: timestamp("login_at", { mode: 'string' }).defaultNow(),
	lastActivityAt: timestamp("last_activity_at", { mode: 'string' }).defaultNow(),
	expiresAt: timestamp("expires_at", { mode: 'string' }).notNull(),
	isActive: boolean("is_active").default(true),
});

export const applicationModules = pgTable("application_modules", {
	moduleId: uuid("module_id").defaultRandom().primaryKey().notNull(),
	appId: uuid("app_id").references(() => applications.appId),
	moduleCode: varchar("module_code", { length: 50 }).notNull(),
	moduleName: varchar("module_name", { length: 100 }).notNull(),
	description: text("description"),
	isCore: boolean("is_core").default(false),
	permissions: jsonb("permissions"),
	createdAt: timestamp("created_at", { mode: 'string' }).defaultNow(),
});

export const customRoles = pgTable("custom_roles", {
	roleId: uuid("role_id").defaultRandom().primaryKey().notNull(),
	tenantId: uuid("tenant_id").notNull().references(() => tenants.tenantId),
	roleName: varchar("role_name", { length: 100 }).notNull(),
	description: text("description"),
	color: varchar("color", { length: 7 }).default('#6b7280'::character varying),
	permissions: jsonb("permissions").notNull(),
	restrictions: jsonb("restrictions").default({}),
	isSystemRole: boolean("is_system_role").default(false),
	isDefault: boolean("is_default").default(false),
	priority: integer("priority").default(0),
	createdBy: uuid("created_by").notNull().references(() => tenantUsers.userId),
	lastModifiedBy: uuid("last_modified_by").references(() => tenantUsers.userId),
	createdAt: timestamp("created_at", { mode: 'string' }).defaultNow(),
	updatedAt: timestamp("updated_at", { mode: 'string' }).defaultNow(),
	kindeRoleId: varchar("kinde_role_id", { length: 255 }),
	kindeRoleKey: varchar("kinde_role_key", { length: 255 }),
});

export const ssoTokens = pgTable("sso_tokens", {
	tokenId: uuid("token_id").defaultRandom().primaryKey().notNull(),
	userId: uuid("user_id").references(() => tenantUsers.userId),
	appId: uuid("app_id").references(() => applications.appId),
	token: text("token").notNull(),
	expiresAt: timestamp("expires_at", { mode: 'string' }).notNull(),
	isRevoked: boolean("is_revoked").default(false),
	createdAt: timestamp("created_at", { mode: 'string' }).defaultNow(),
});

export const subscriptions = pgTable("subscriptions", {
	subscriptionId: uuid("subscription_id").defaultRandom().primaryKey().notNull(),
	tenantId: uuid("tenant_id").notNull().references(() => tenants.tenantId),
	stripeSubscriptionId: varchar("stripe_subscription_id", { length: 255 }),
	stripeCustomerId: varchar("stripe_customer_id", { length: 255 }),
	stripePriceId: varchar("stripe_price_id", { length: 255 }),
	plan: varchar("plan", { length: 50 }).notNull(),
	status: varchar("status", { length: 20 }).notNull(),
	subscribedTools: jsonb("subscribed_tools").default([]),
	usageLimits: jsonb("usage_limits").default({}),
	monthlyPrice: numeric("monthly_price", { precision: 10, scale:  2 }).default('0'),
	yearlyPrice: numeric("yearly_price", { precision: 10, scale:  2 }).default('0'),
	billingCycle: varchar("billing_cycle", { length: 20 }).default('monthly'::character varying),
	currentPeriodStart: timestamp("current_period_start", { mode: 'string' }),
	currentPeriodEnd: timestamp("current_period_end", { mode: 'string' }),
	canceledAt: timestamp("canceled_at", { mode: 'string' }),
	trialStart: timestamp("trial_start", { mode: 'string' }),
	trialEnd: timestamp("trial_end", { mode: 'string' }),
	createdAt: timestamp("created_at", { mode: 'string' }).defaultNow(),
	updatedAt: timestamp("updated_at", { mode: 'string' }).defaultNow(),
	firstUpgradeAt: timestamp("first_upgrade_at", { mode: 'string' }),
	lastDowngradeAt: timestamp("last_downgrade_at", { mode: 'string' }),
	trialToggledOff: boolean("trial_toggled_off").default(false),
	isTrialUser: boolean("is_trial_user").default(false),
	hasEverUpgraded: boolean("has_ever_upgraded").default(false),
	cancelationReason: text("cancelation_reason"),
	lastReminderSentAt: timestamp("last_reminder_sent_at", { mode: 'string' }),
	reminderCount: integer("reminder_count").default(0),
	restrictionsAppliedAt: timestamp("restrictions_applied_at", { mode: 'string' }),
	cancelAt: timestamp("cancel_at", { mode: 'string' }),
	suspendedAt: timestamp("suspended_at", { mode: 'string' }),
	suspendedReason: text("suspended_reason"),
	addOns: jsonb("add_ons").default([]),
});

export const tenantInvitations = pgTable("tenant_invitations", {
	invitationId: uuid("invitation_id").defaultRandom().primaryKey().notNull(),
	tenantId: uuid("tenant_id").notNull().references(() => tenants.tenantId),
	email: varchar("email", { length: 255 }).notNull(),
	roleId: uuid("role_id"),
	invitedBy: uuid("invited_by").notNull(),
	invitationToken: varchar("invitation_token", { length: 255 }).notNull(),
	status: varchar("status", { length: 20 }).default('pending'::character varying),
	expiresAt: timestamp("expires_at", { mode: 'string' }).notNull(),
	acceptedAt: timestamp("accepted_at", { mode: 'string' }),
	createdAt: timestamp("created_at", { mode: 'string' }).defaultNow(),
	invitationUrl: varchar("invitation_url", { length: 1000 }),
	cancelledAt: timestamp("cancelled_at", { mode: 'string' }),
	cancelledBy: uuid("cancelled_by"),
	updatedAt: timestamp("updated_at", { mode: 'string' }).defaultNow(),
},
(table) => {
	return {
		idxTenantInvitationsEmail: index("idx_tenant_invitations_email").on(table.email),
		idxTenantInvitationsStatus: index("idx_tenant_invitations_status").on(table.status),
		idxTenantInvitationsToken: index("idx_tenant_invitations_token").on(table.invitationToken),
		tenantInvitationsInvitationTokenUnique: unique("tenant_invitations_invitation_token_unique").on(table.invitationToken),
	}
});

export const usageLogs = pgTable("usage_logs", {
	logId: uuid("log_id").defaultRandom().primaryKey().notNull(),
	tenantId: uuid("tenant_id").notNull().references(() => tenants.tenantId),
	userId: uuid("user_id").references(() => tenantUsers.userId),
	app: varchar("app", { length: 50 }).notNull(),
	endpoint: varchar("endpoint", { length: 255 }).notNull(),
	method: varchar("method", { length: 10 }).notNull(),
	statusCode: integer("status_code"),
	responseTime: numeric("response_time", { precision: 8, scale:  2 }),
	source: varchar("source", { length: 50 }).notNull(),
	ipAddress: varchar("ip_address", { length: 45 }),
	userAgent: text("user_agent"),
	requestSize: integer("request_size"),
	responseSize: integer("response_size"),
	metadata: jsonb("metadata").default({}),
	errorMessage: text("error_message"),
	errorStack: text("error_stack"),
	createdAt: timestamp("created_at", { mode: 'string' }).defaultNow(),
});

export const usageMetricsDaily = pgTable("usage_metrics_daily", {
	metricId: uuid("metric_id").defaultRandom().primaryKey().notNull(),
	tenantId: uuid("tenant_id").notNull().references(() => tenants.tenantId),
	app: varchar("app", { length: 50 }).notNull(),
	date: timestamp("date", { mode: 'string' }).notNull(),
	apiCalls: integer("api_calls").default(0),
	storageUsed: numeric("storage_used", { precision: 15, scale:  2 }).default('0'),
	activeUsers: integer("active_users").default(0),
	totalRequests: integer("total_requests").default(0),
	avgResponseTime: numeric("avg_response_time", { precision: 8, scale:  2 }).default('0'),
	errorCount: integer("error_count").default(0),
	featureUsage: jsonb("feature_usage").default({}),
	usageBySource: jsonb("usage_by_source").default({}),
	createdAt: timestamp("created_at", { mode: 'string' }).defaultNow(),
	updatedAt: timestamp("updated_at", { mode: 'string' }).defaultNow(),
});

export const userApplicationPermissions = pgTable("user_application_permissions", {
	id: uuid("id").defaultRandom().primaryKey().notNull(),
	userId: uuid("user_id").references(() => tenantUsers.userId),
	appId: uuid("app_id").references(() => applications.appId),
	moduleId: uuid("module_id").references(() => applicationModules.moduleId),
	permissions: jsonb("permissions"),
	isActive: boolean("is_active").default(true),
	grantedBy: uuid("granted_by").references(() => tenantUsers.userId),
	grantedAt: timestamp("granted_at", { mode: 'string' }).defaultNow(),
	expiresAt: timestamp("expires_at", { mode: 'string' }),
});

export const webhookLogs = pgTable("webhook_logs", {
	id: uuid("id").defaultRandom().primaryKey().notNull(),
	eventId: varchar("event_id", { length: 255 }).notNull(),
	eventType: varchar("event_type", { length: 100 }).notNull(),
	status: varchar("status", { length: 50 }).notNull(),
	errorMessage: text("error_message"),
	createdAt: timestamp("created_at", { mode: 'string' }).defaultNow(),
	updatedAt: timestamp("updated_at", { mode: 'string' }).defaultNow(),
},
(table) => {
	return {
		webhookLogsEventIdUnique: unique("webhook_logs_event_id_unique").on(table.eventId),
	}
});